let phone ={name:"Iphone 16 pro",price:120000,deliveryDate:"11-06-2026"}
console.log(typeof phone);

const phones = [
  {
    brand: "Apple",
    productName: "iPhone 17e 256 GB",
    display: "6.1-inch Super Retina XDR",
    chip: "A19 Chip",
    battery: "All-Day Battery Life",
    camera: "48MP Fusion Camera",
    storage: "256GB",
    color: "Black",
    rating: 4.4,
    ratingsCount: 41,
    boughtPastMonth: "500+",
    price: 64900,
    currency: "INR",
    delivery: "Mon, 15 Jun",
    emiAvailable: true,
    asin: "APL001",
    merchantId: "MER001"
  },
  {
    brand: "Samsung",
    productName: "Galaxy S25 Ultra",
    display: "6.8-inch Dynamic AMOLED 2X",
    chip: "Snapdragon 8 Elite",
    battery: "5000mAh",
    camera: "200MP Quad Camera",
    storage: "512GB",
    color: "Titanium Gray",
    rating: 4.7,
    ratingsCount: 1250,
    boughtPastMonth: "2K+",
    price: 124999,
    currency: "INR",
    delivery: "Tue, 16 Jun",
    emiAvailable: true,
    asin: "SAM001",
    merchantId: "MER002"
  },
  {
    brand: "Google",
    productName: "Pixel 10 Pro",
    display: "6.7-inch LTPO OLED",
    chip: "Tensor G5",
    battery: "5100mAh",
    camera: "50MP Triple Camera",
    storage: "256GB",
    color: "Porcelain",
    rating: 4.6,
    ratingsCount: 842,
    boughtPastMonth: "1K+",
    price: 89999,
    currency: "INR",
    delivery: "Wed, 17 Jun",
    emiAvailable: true,
    asin: "GOO001",
    merchantId: "MER003"
  },
  {
    brand: "OnePlus",
    productName: "OnePlus 14",
    display: "6.82-inch AMOLED",
    chip: "Snapdragon 8 Gen 4",
    battery: "5500mAh",
    camera: "50MP Hasselblad Camera",
    storage: "256GB",
    color: "Emerald Green",
    rating: 4.5,
    ratingsCount: 620,
    boughtPastMonth: "900+",
    price: 69999,
    currency: "INR",
    delivery: "Thu, 18 Jun",
    emiAvailable: true,
    asin: "ONE001",
    merchantId: "MER004"
  },
  {
    brand: "Xiaomi",
    productName: "Xiaomi 15 Ultra",
    display: "6.73-inch AMOLED",
    chip: "Snapdragon 8 Elite",
    battery: "5300mAh",
    camera: "200MP Leica Camera",
    storage: "512GB",
    color: "White",
    rating: 4.4,
    ratingsCount: 410,
    boughtPastMonth: "700+",
    price: 79999,
    currency: "INR",
    delivery: "Fri, 19 Jun",
    emiAvailable: true,
    asin: "XIA001",
    merchantId: "MER005"
  },
  {
    brand: "Vivo",
    productName: "Vivo X200 Pro",
    display: "6.78-inch AMOLED",
    chip: "Dimensity 9500",
    battery: "6000mAh",
    camera: "200MP ZEISS Camera",
    storage: "256GB",
    color: "Blue",
    rating: 4.3,
    ratingsCount: 385,
    boughtPastMonth: "650+",
    price: 74999,
    currency: "INR",
    delivery: "Sat, 20 Jun",
    emiAvailable: true,
    asin: "VIV001",
    merchantId: "MER006"
  },
  {
    brand: "Oppo",
    productName: "Find X9 Pro",
    display: "6.82-inch AMOLED",
    chip: "Dimensity 9500",
    battery: "5800mAh",
    camera: "50MP Quad Camera",
    storage: "512GB",
    color: "Black",
    rating: 4.2,
    ratingsCount: 290,
    boughtPastMonth: "450+",
    price: 72999,
    currency: "INR",
    delivery: "Mon, 22 Jun",
    emiAvailable: true,
    asin: "OPP001",
    merchantId: "MER007"
  },
  {
    brand: "Realme",
    productName: "GT 8 Pro",
    display: "6.78-inch AMOLED",
    chip: "Snapdragon 8 Gen 4",
    battery: "6000mAh",
    camera: "108MP Triple Camera",
    storage: "256GB",
    color: "Silver",
    rating: 4.1,
    ratingsCount: 520,
    boughtPastMonth: "800+",
    price: 54999,
    currency: "INR",
    delivery: "Tue, 23 Jun",
    emiAvailable: true,
    asin: "REA001",
    merchantId: "MER008"
  },
  {
    brand: "Motorola",
    productName: "Edge 70 Ultra",
    display: "6.7-inch pOLED",
    chip: "Snapdragon 8 Gen 4",
    battery: "5000mAh",
    camera: "50MP Triple Camera",
    storage: "256GB",
    color: "Forest Green",
    rating: 4.3,
    ratingsCount: 340,
    boughtPastMonth: "400+",
    price: 64999,
    currency: "INR",
    delivery: "Wed, 24 Jun",
    emiAvailable: true,
    asin: "MOT001",
    merchantId: "MER009"
  },
  {
    brand: "Nothing",
    productName: "Phone (4) Pro",
    display: "6.77-inch AMOLED",
    chip: "Snapdragon 8s Gen 4",
    battery: "5200mAh",
    camera: "50MP Triple Camera",
    storage: "256GB",
    color: "Transparent",
    rating: 4.5,
    ratingsCount: 610,
    boughtPastMonth: "1.2K+",
    price: 59999,
    currency: "INR",
    delivery: "Thu, 25 Jun",
    emiAvailable: true,
    asin: "NOT001",
    merchantId: "MER010"
  }
];

console.log(phones);